export const images = {
  loaderBg:   require('./resort-assistant-loader-bg.png'),
  loaderIcon: require('./resort-assistant-loader-icon.png'),
  onboardBg1: require('./resort-assistant-onboard-bg1.png'),
  onboardBg2: require('./resort-assistant-onboard-bg2.png'),
  onboardBg3: require('./resort-assistant-onboard-bg3.png'),
  onboardBg4: require('./resort-assistant-onboard-bg4.png'),
  onboardBg5: require('./resort-assistant-onboard-bg5.png'),

  MediterraneanBreakfastPlate: require('./resort-assistant-mediterranean-breakfast-plate.png'),
  GoldenOmelette:              require('./resort-assistant-golden-omelette.png'),
  FreshCroissantSet:           require('./resort-assistant-fresh-croissant-set.png'),
  YogurtBerryBowl:             require('./resort-assistant-yogurt-berry-bowl.png'),
  AvocadoToast:                require('./resort-assistant-avocado-toast.png'),
  GrilledSeaBass:              require('./resort-assistant-grilled-sea-bass.png'),
  TruffleChickenFillet:        require('./resort-assistant-truffle-chicken-fillet.png'),
  BeefTenderloin:              require('./resort-assistant-beef-tenderloin.png'),
  CreamyMushroomRisotto:       require('./resort-assistant-creamy-mushroom-risotto.png'),
  SeafoodLinguine:             require('./resort-assistant-seafood-linguine.png'),
  SignatureClubSandwich:       require('./resort-assistant-signature-club-sandwich.png'),
  CaesarSaladDeluxe:           require('./resort-assistant-caesar-salad-deluxe.png'),
  LocalGrilledVegetables:      require('./resort-assistant-local-grilled-vegetables.png'),
  ChocolateFondant:            require('./resort-assistant-chocolate-fondant.png'),
  PistachioCheesecake:         require('./resort-assistant-pistachio-cheesecake.png'),
  HoneyBaklavaPlate:           require('./resort-assistant-honey-baklava-plate.png'),
  VanillaBerryPannaCotta:      require('./resort-assistant-vanilla-berry-panna-cotta.png'),
  GoldenCitrusLemonade:        require('./resort-assistant-golden-citrus-lemonade.png'),
  IcedCoffee:                  require('./resort-assistant-iced-coffee.png'),
  BerryMocktail:               require('./resort-assistant-berry-mocktail.png'),

  ExtraPillows:   require('./resort-assistant-extra-pillows.png'),
  FreshTowels:    require('./resort-assistant-fresh-towels.png'),
  Bathrobes:      require('./resort-assistant-bathrobes.png'),
  BottledWater:   require('./resort-assistant-bottled-water.png'),
  ExtraBlankets:  require('./resort-assistant-extra-blankets.png'),
  ToiletryKit:    require('./resort-assistant-toiletry-kit.png'),
  RoomCleaning:   require('./resort-assistant-room-cleaning.png'),
  LaundryPickup:  require('./resort-assistant-laundry-pickup.png'),

  GdanskOldTown:              require('./resort-assistant-gdansk-old-town.png'),
  NeptuneFountain:            require('./resort-assistant-neptune-fountain.png'),
  StMarysChurch:              require('./resort-assistant-st-marys-church.png'),
  MotlawaRiverPromenade:      require('./resort-assistant-motlawa-river-promenade.png'),
  EuropeanSolidarityCentre:   require('./resort-assistant-european-solidarity-centre.png'),
  MuseumOfTheSecondWorldWar:  require('./resort-assistant-museum-of-the-second-world-war.png'),
  WesterplatteMemorial:       require('./resort-assistant-westerplatte-memorial.png'),
  AmberSkyFerrisWheel:        require('./resort-assistant-amber-sky-ferris-wheel.png'),
  OliwaCathedral:             require('./resort-assistant-oliwa-cathedral.png'),
  OliwaPark:                  require('./resort-assistant-oliwa-park.png'),
  SopotPier:                  require('./resort-assistant-sopot-pier.png'),
  BrzeznoBeach:               require('./resort-assistant-brzezno-beach.png'),
} as const;

export type ImageKey = keyof typeof images;
